// Generated by Wrangler by running `wrangler types`

interface Env {
	LEADERBOARD: KVNamespace;
	OPENAI_API_KEY: string;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
	PUBLISH: Workflow;
	INTERACTION: Workflow;
	LEADERBOARD_WORKFLOW: Workflow;
	PUNTIFICATOR: Workflow;
}
